//////////////////////////////////////////////
// AVR WATCH DOG TIMER LIBRARY
//
// IF WATCHDOG TIMER ON (WTDON) FUSE IS
// PROGRAMMED / ENABLED THE ONLY MODE WDT 
// CAN WORK IS IN SYSTEM RESET MODE
//
// DECEMBER 22, 2016
//
// ANKIT BHATNAGAR
// ANKIT.BHATNAGARINDIA@GMAIL.COM
//////////////////////////////////////////////

#include "AVR_WDT.h"

void AVR_WDT_Enable(uint8_t wdt_mode, uint8_t wdt_prescale)
{
	//ENABLE WATCH DOG TIMER (WDT) IN
	//THE SPECIFIED MODE AND WITH SPECIFIED
	//TIME PERIOD
	//GLOBAL INTERRUPTS DISABLED FOR THE DURATION OF 
	//EXECUTION OF THIS FUNCTION !
	
	//DISBALE GLOBAL INTERRUPTS
	cli();
	
	//CLEAR THE EXISTING MODE
	AVR_WDT_Disable();
	
	//CLEAR EXISITING PRESCALE
	WDTCSR &= ~((1 << WDP3) | (1 << WDP2) | (1 << WDP1) | (1 << WDP0));
	
	//SET NEW PRESCALE VALUE
	WDTCSR |= wdt_prescale;
	
	//SET THE NEW MODE
	WDTCST |= wdt_mode;
	
	//ENABLE GLOBAL INTERRUPTS
	sei();
}

void AVR_WDT_Clear_Reset_Flag(void)
{
	//CLEAR THE WDT RESET FLAG IF PRESENT
	//AS THIS IS NOT DONE AUTOMATICALLY BY THE
	//SYSTEM UPTON WDT SYSTEM RESET

	MCUSR &= ~(1 << WDRF);
}

void AVR_WDT_Reset(void);
{
	//RESET THE WATCH DOG TIMER (WDT)
	
	wdt_reset();
}

void AVR_WDT_Disable(void)
{
	//DISABLE THE WATCH DOG TIMER (WDT)
	//CLEARS THE WDT TIMER COUNT ALSO
	//EXTERNAL GLOBAL INTERRUPTS DISABLED FOR THE
	//DURATION OF EXECUTION OF THIS FUNCTION !

	//DISABLE GLOBAL INTERRUPTS
	cli();
	
	//RESET WATCHDOG
	AVR_WDT_Reset();
	
	//CLEAR WDT RESET FLAG
	AVR_WDT_Clear_Reset_Flag();
	
	WDTCSR = 0x00;
	
	//ENABLE GLOBAL INTERRUPTS
	sei();
}