//////////////////////////////////////////////
// AVR WATCH DOG TIMER LIBRARY
//
// IF WATCHDOG TIMER ON (WTDON) FUSE IS
// PROGRAMMED / ENABLED THE ONLY MODE WDT 
// CAN WORK IS IN SYSTEM RESET MODE
//
// NOTE : BEFORE DOING ANY KIND OF OPERATION
//		  ON WATCHDOG, MAKE SURE TO DISABLE
//		  GLOBAL INTERRUPTS ! USERS
//		  RESPONSIBILITY. THE LIBRARY WON'T
//		  DO IT AUTOMATICALLY !!
//
// DECEMBER 22, 2016
//
// ANKIT BHATNAGAR
// ANKIT.BHATNAGARINDIA@GMAIL.COM
//////////////////////////////////////////////

#include "AVR_WDT.h"

void AVR_WDT_Enable(uint8_t wdt_mode, uint8_t wdt_prescale)
{
	//ENABLE WATCH DOG TIMER (WDT) IN
	//THE SPECIFIED MODE AND WITH SPECIFIED
	//TIME PERIOD
	//GLOBAL INTERRUPTS DISABLED FOR THE DURATION OF 
	//EXECUTION OF THIS FUNCTION !
	
	//ENABLE WATCHDOG CHANGE ENABLE
	WDTCSR |= ((1 << WDCE) | (1 << WDE));	
	
	//CLEAR EXISITING PRESCALE
	WDTCSR &= ~((1 << WDP3) | (1 << WDP2) | (1 << WDP1) | (1 << WDP0));
	
	//SET NEW PRESCALE VALUE
	WDTCSR |= wdt_prescale;
	
	//SET THE NEW MODE
	WDTCST |= wdt_mode;
}

uint8_t AVR_WDT_Check_Reset_Flag(void)
{
	//CHECK THE WDRF FLAG IN MCUSR TO
	//SEE IF THE MCU GOT RESET BECAUSE OF
	//WATCHDOG TIMEOUT
	
	if(MCUSR & (1 << WDRF))
	{
		return 1;
	}
	return 0;
}

void AVR_WDT_Clear_Reset_Flag(void)
{
	//CLEAR THE WDT RESET FLAG IF PRESENT
	//AS THIS IS NOT DONE AUTOMATICALLY BY THE
	//SYSTEM UPON WDT SYSTEM RESET AND DISABLE WATCHDOG
	//NOTE: ONLY REQUIRED FOR NEVER AVR SUPPORTING
	//WDT INTERRUPT MODE !
	
	//CLEAR FLAG
	MCUSR &= ~(1 << WDRF);
}

void AVR_WDT_Reset(void);
{
	//RESET THE WATCH DOG TIMER (WDT)
	//TO PREVENT WDT TIMEOUT
	
	wdt_reset();
}

void AVR_WDT_Disable(void)
{
	//DISABLE THE WATCH DOG TIMER (WDT)
	//CLEARS THE WDT TIMER COUNT ALSO
	//EXTERNAL GLOBAL INTERRUPTS DISABLED FOR THE
	//DURATION OF EXECUTION OF THIS FUNCTION !

	//ENABLE WATCHDOG CHANGE ENABLE
	WDTCSR |= ((1 << WDCE) | (1 << WDE));
	
	//DISABLE WATCHDOG
	wdt_disable();
}